---
- name: "Install Nginx"
  apt:
    name: nginx
    state: latest
  tags:
    - nginx

- name: "Install python3"
  apt:
    name: python3
    state: latest
  tags:
    - python

- name: "Install certbot"
  apt:
    name: certbot
    state: latest
  tags:
    - certbot
  
- name: "Install python3-certbot-nginx"
  apt:
    name: python3-certbot-nginx
    state: latest
  tags:
    - certbot
    - nginx
  
...